### ISSUE TITLE
Need to deal with R 4.2.0

### ISSUE THREAD

**Issue by inoue0426** [KlugerLab/ALRA#18]
Hi,

I found this library doesn't work because of the change by R 4.2.0.

`if (class(A_norm) != 'matrix') {` doesn't work and it should use `if (!(any(grepl("matrix", class(A_norm), ignore.case = TRUE)))) {`

Can I make a Pull Request for that?

**Comment by SamGG** [comment]
Could it be simpler?
```
!('matrix' %in% class(A_norm))
all(class(A_norm) != 'matrix')
```

**Comment by inoue0426** [comment]
Looks good to me!

**Comment by linqiaozhi** [comment]
Yes, please make a PR. Thanks so much. @inoue0426

**Comment by inoue0426** [comment]
#19 This is merged to main. So close to this issue.
