### ISSUE TITLE
alraSeurat2 FUNCTION NOT FOUND!!!!

### ISSUE THREAD

**Issue by EDYAC** [KlugerLab/ALRA#2]
Hello Everyone,
I have installed the rsvd package, when I try to run the alraSeurat2 function, it return an error, saying that the function is not found.
Any idea what is going wrong?
Thank you.

**Comment by JunZhao1990** [comment]
Please run these two lines to source the functions:

source("https://raw.githubusercontent.com/KlugerLab/ALRA/master/alra.R")
source("https://raw.githubusercontent.com/KlugerLab/ALRA/master/alraSeurat2.R")

Jun

**Comment by EDYAC** [comment]
Hey @JunZhao1990 ,
Thank you for your reply, it's working now!
I do have a question, if I have two samples, 1 control and 1 stimulated, do I merge the two datasets and then do imputation or I do imputation first then merge?
Thank you.

**Comment by linqiaozhi** [comment]
@EDYAC, from our experience, it seems that merging and then imputing is best. This also seems to be the experience of [these](https://www.biorxiv.org/content/10.1101/568659v1) authors, who report ALRA being actually helpful in removing the batch effect when applied to the merged.  Their code is [here](https://vanandelinstitute.github.io/va_ecls/final_analysis.html). 

If you have other questions regarding multiple samples, please open a separate issue--it helps others find it more easily.
