### ISSUE TITLE
Input format (genes as rows?)

### ISSUE THREAD

**Issue by anacarolinaleote** [KlugerLab/ALRA#9]
Thank you for the interesting approach to dropout imputation! I know it's documented, but different parts of the documentation say different things: should the input matrix have genes as rows and cells as columns or the other way around? Thanks!

**Comment by JunZhao1990** [comment]
Thank you for your interest in ALRA.
If you use the function `alra()` directly, the input matrix should have cells in rows and genes in columns. The function `alraSeurat2()` will take a Seurat v2 object directly.
